root = "."
tmp_dir = "/tmp/air"

[build]
  cmd = "go build -buildvcs=false -o /tmp/air/api ./cmd/server"
  entrypoint = "/tmp/air/api"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "bin"]
  exclude_file = ["*_test.go"]
  delay = 1000
  stop_on_error = true

[log]
  time = true

[screen]
  clear_on_rebuild = true
